const sampleListings = [
  {
    title: "The Arowana Luxury Villa",
    description: "Experience luxury living with premium amenities and breathtaking surroundings.",
    image: "https://thearowanavilla.com/uploads/project/2fa34507cf904a2c928b061bfc3d493c.jpg",
    price: 8500,
    location: "Lonavala",
    country: "India",
  },
  {
    title: "Private Pool Villa",
    description: "Relax in a beautiful villa featuring a private swimming pool.",
    image: "https://thearowanavilla.com/uploads/project/2c22e95c7b2e7ee890bc7f00bcaaacc9.jpeg",
    price: 9200,
    location: "Goa",
    country: "India",
  },
  {
    title: "Modern Family Retreat",
    description: "A spacious villa perfect for family vacations and weekend getaways.",
    image: "https://thearowanavilla.com/uploads/project/1b01018466e8ed242f69ad3656fcfa2f.jpg",
    price: 7800,
    location: "Mahabaleshwar",
    country: "India",
  },
  {
    title: "Elegant Mansion",
    description: "A luxurious mansion with elegant interiors and open spaces.",
    image: "https://thearowanavilla.com/uploads/project/03f3dc07c43f7154d4e900926ee294111.jpg",
    price: 12000,
    location: "Jaipur",
    country: "India",
  },
  {
    title: "The Arowana Mansion",
    description: "Premium accommodation with world-class comfort.",
    image: "https://thearowanavilla.com/uploads/project/The_Arowana_Mansion110.jpeg",
    price: 15000,
    location: "Lonavala",
    country: "India",
  },
  {
    title: "Luxury Garden Villa",
    description: "Wake up to peaceful garden views in this premium villa.",
    image: "https://thearowanavilla.com/uploads/project/WhatsApp_Image_2024-02-28_at_11_14_283.jpeg",
    price: 8700,
    location: "Pune",
    country: "India",
  },
  {
    title: "Premium Vacation Home",
    description: "Modern architecture with spacious rooms and luxurious amenities.",
    image: "https://thearowanavilla.com/uploads/project/WhatsApp_Image_2024-02-28_at_11_14_28_(10)21.jpeg",
    price: 8300,
    location: "Nashik",
    country: "India",
  },
  {
    title: "Scenic Pool House",
    description: "Perfect destination for a relaxing vacation with family.",
    image: "https://thearowanavilla.com/uploads/project/WhatsApp_Image_2024-02-28_at_11_14_28_(9)21.jpeg",
    price: 7900,
    location: "Alibaug",
    country: "India",
  },
  {
    title: "Grand Luxury Estate",
    description: "An exclusive property designed for memorable stays.",
    image: "https://thearowanavilla.com/uploads/project/image00005.jpeg",
    price: 9800,
    location: "Udaipur",
    country: "India",
  },
  {
    title: "Infinity Pool Villa",
    description: "Enjoy panoramic views from the infinity pool.",
    image: "https://thearowanavilla.com/uploads/project/WhatsApp_Image_2024-02-28_at_11_14_28_(32)1.jpeg",
    price: 9100,
    location: "Goa",
    country: "India",
  },
  {
    title: "Designer Villa",
    description: "Luxury interiors crafted with modern elegance.",
    image: "https://thearowanavilla.com/uploads/project/WhatsApp_Image_2024-02-28_at_11_14_28_(30)1.jpeg",
    price: 8600,
    location: "Hyderabad",
    country: "India",
  },
  {
    title: "Royal Holiday Home",
    description: "A perfect combination of comfort and sophistication.",
    image: "https://thearowanavilla.com/uploads/project/WhatsApp_Image_2024-02-28_at_11_14_28_(17)11.jpeg",
    price: 8900,
    location: "Mysore",
    country: "India",
  },
  {
    title: "Luxury Weekend Escape",
    description: "Spend quality time in this peaceful luxury villa.",
    image: "https://thearowanavilla.com/uploads/project/WhatsApp_Image_2024-02-28_at_11_14_28_(8)21.jpeg",
    price: 7600,
    location: "Coorg",
    country: "India",
  },
  {
    title: "Outdoor Paradise Villa",
    description: "Beautiful outdoor seating and landscaped surroundings.",
    image: "https://thearowanavilla.com/uploads/project/1_Outdoor_House_41.jpg",
    price: 8700,
    location: "Lonavala",
    country: "India",
  },
  {
    title: "Outdoor Lounge Villa",
    description: "Relax in stylish outdoor spaces with scenic views.",
    image: "https://thearowanavilla.com/uploads/project/3_Outdoor_sitting_2.jpg",
    price: 8200,
    location: "Panchgani",
    country: "India",
  },
  {
    title: "Luxury Garden Retreat",
    description: "A peaceful escape surrounded by lush greenery.",
    image: "https://thearowanavilla.com/uploads/project/5_Outdoor_4.jpg",
    price: 8100,
    location: "Ooty",
    country: "India",
  },
  {
    title: "Fountain View Villa",
    description: "Elegant villa with a beautiful fountain at its entrance.",
    image: "https://thearowanavilla.com/uploads/project/9_Fountain_.jpg",
    price: 9500,
    location: "Jaipur",
    country: "India",
  },
  {
    title: "Nature Inspired Villa",
    description: "Enjoy a refreshing stay surrounded by nature.",
    image: "https://thearowanavilla.com/uploads/project/6_Outdoor_3.jpg",
    price: 8000,
    location: "Munnar",
    country: "India",
  },
  {
    title: "Bonfire Retreat",
    description: "Spend cozy evenings around a private bonfire.",
    image: "https://thearowanavilla.com/uploads/project/912_Bonfire_2.jpg",
    price: 9300,
    location: "Manali",
    country: "India",
  },
  {
    title: "Lake View Luxury Villa",
    description: "A serene villa overlooking a peaceful lake.",
    image: "https://thearowanavilla.com/uploads/project/914_Lake.jpg",
    price: 9700,
    location: "Udaipur",
    country: "India",
  },
];

module.exports = { data: sampleListings };