module.exports =  [

  { sender: "Bhushan", receiver: "Rahul", message: "Hey Rahul, are you free?" },
  { sender: "Rahul", receiver: "Bhushan", message: "Yes, what's up?" },
  { sender: "Bhushan", receiver: "Rahul", message: "Need help with the MongoDB project." },
  { sender: "Rahul", receiver: "Bhushan", message: "Sure, send me your code." },
  { sender: "Bhushan", receiver: "Rahul", message: "I've sent it on GitHub." },
  { sender: "Rahul", receiver: "Bhushan", message: "I'll check it tonight." },
  { sender: "Amit", receiver: "Sneha", message: "Good morning!" },
  { sender: "Sneha", receiver: "Amit", message: "Morning! Ready for class?" },
  { sender: "Amit", receiver: "Sneha", message: "Almost, leaving in 10 minutes." },
  { sender: "Sneha", receiver: "Amit", message: "I'll save a seat for you." },
  { sender: "Amit", receiver: "Sneha", message: "Thanks!" },
  { sender: "Priya", receiver: "Rohan", message: "Did you complete the assignment?" },
  { sender: "Rohan", receiver: "Priya", message: "Not yet." },
  { sender: "Priya", receiver: "Rohan", message: "Submission is tomorrow." },
  { sender: "Rohan", receiver: "Priya", message: "I'll finish it tonight." },
  { sender: "Priya", receiver: "Rohan", message: "Great, let me know if you need help." },
  { sender: "Neha", receiver: "Karan", message: "Where are you?" },
  { sender: "Karan", receiver: "Neha", message: "In the library." },
  { sender: "Neha", receiver: "Karan", message: "Can you bring my notebook?" },
  { sender: "Karan", receiver: "Neha", message: "Sure." },
  { sender: "Neha", receiver: "Karan", message: "Thanks!" },
  { sender: "Bhushan", receiver: "Sneha", message: "Can you share yesterday's notes?" },
  { sender: "Sneha", receiver: "Bhushan", message: "Yes, I'll send the PDF." },
  { sender: "Bhushan", receiver: "Sneha", message: "Thank you!" },
  { sender: "Sneha", receiver: "Bhushan", message: "You're welcome." },
  { sender: "Rahul", receiver: "Amit", message: "Football this evening?" },
  { sender: "Amit", receiver: "Rahul", message: "Definitely!" },
  { sender: "Rahul", receiver: "Amit", message: "Let's meet at 6 PM." },
  { sender: "Amit", receiver: "Rahul", message: "See you then." },
  { sender: "Rohan", receiver: "Karan", message: "Are you coming to the hackathon?" },
  { sender: "Karan", receiver: "Rohan", message: "Yes, I've already registered." },
  { sender: "Rohan", receiver: "Karan", message: "Awesome, let's form a team." },
  { sender: "Karan", receiver: "Rohan", message: "Done!" }
  
];